version: "3"
services:
  mosquitto:
    image: iegomez/mosquitto-go-auth:2.1.0-mosquitto_1.6.14
    container_name: mosquitto-container
    restart: always
    volumes:
      - ../../config/certs:/etc/mosquitto/certs
      - ./mosquitto/config/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 8883:8883
      - 8884:8884
      - 9001:9001
    networks:
      - app-network

networks:
  app-network:
    external: true
