<?php

const ROOT = __DIR__ . DIRECTORY_SEPARATOR;
const CONTROLLER = ROOT . "Controller" . DIRECTORY_SEPARATOR;
const CORE = ROOT . "Core" . DIRECTORY_SEPARATOR;
const DATA = ROOT . "Data" . DIRECTORY_SEPARATOR;
const HELPER = ROOT . "Helper" . DIRECTORY_SEPARATOR;
const MODEL = ROOT . "Model" . DIRECTORY_SEPARATOR;
const TEMPLATES = ROOT . "Templates" . DIRECTORY_SEPARATOR;
const VIEW = ROOT . "View" . DIRECTORY_SEPARATOR;
