version: '3.8'

services:
  device-api:
    build: .
    container_name: device-api-container
    restart: always
    env_file:
      - ../../config/env/.env
    ports:
      - "3001:443"
    volumes:
      - ../../config/certs:/etc/apache2/ssl
      - ./src/Public:/var/www/html
      - ./src/Api:/var/www/Api
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    networks:
      - app-network

networks:
  app-network:
    external: true
