# MQTT Auth Service (Bu Servis Mosquitto Container'ı Tarafından Kullanılır. Dışarısı Erişemez.)
server {
    listen 80;

    root /var/www/mqtt/public;
    index index.php index.html;

    location / {
        try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass mqtt-php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}

# Firmware Update Service (mTLS)
server {
    listen 443 ssl;
    # server_name ota.rows.local;

    root /var/www/ota/public;
    index index.php index.html;

    # Sunucu Sertifikası
    ssl_certificate     /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    # İstemci Sertifikası Doğrulama
    ssl_client_certificate /etc/nginx/certs/ca.crt;
    ssl_verify_client on;
    ssl_verify_depth 1;

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass ota-php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;

        # mTLS bilgileri
        fastcgi_param SSL_CLIENT_VERIFY $ssl_client_verify;
        fastcgi_param SSL_CLIENT_S_DN $ssl_client_s_dn;
        fastcgi_param SSL_CLIENT_I_DN $ssl_client_i_dn;
        fastcgi_param SSL_CLIENT_SERIAL $ssl_client_serial;
        fastcgi_param SSL_CLIENT_CERT $ssl_client_escaped_cert;
    }
}
