version: '3.8'

services:
  ota-service:
    build: .
    container_name: ota-service-container
    restart: always
    env_file:
      - ../../config/env/.env
    ports:
      - "8443:443"
    volumes:
      - ../../config/certs:/etc/apache2/ssl
      - ./src/Public:/var/www/html
      - ./src/App:/var/www/App
      - ./src/Firmwares:/var/www/Firmwares
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    networks:
      - app-network

networks:
  app-network:
    external: true
