[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
monitor_speed = 115200
lib_deps = 
    AsyncTCP
    HTTPClient
    LittleFS
    Update
    LovyanGFX
    WiFi
    WebServer
    PubSubClient
lib_ignore = RPAsyncTCP
build_flags =
    -Wall
    -Wextra
    -Werror
build_src_flags =
    -DDEBUG 
    -DLOG_LEVEL=LOG_LEVEL_INFO
monitor_filters = esp32_exception_decoder
